package dev.meghlath.switchboard.annotations

/**
 * Internal metadata annotation generated by the Switchboard KSP processor.
 *
 * Applied to generated accessor classes or registry aggregators to associate them
 * with their original source container name for reflective or programmatic lookups.
 *
 * **Usage Example:**
 * ```kotlin
 * @FlagContainerMetadata(containerName = "AppFlags")
 * public object AppFlagsFlags { ... }
 * ```
 *
 * @property containerName The simple name of the source class/object annotated with [Flags].
 */
@Retention(AnnotationRetention.BINARY)
@Target(AnnotationTarget.CLASS)
public annotation class FlagContainerMetadata(
    public val containerName: String
)
